---
driver:
  name: terraform

provisioner:
  name: terraform
  variable_files:
    - terraform.tfvars

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ~/.aws/nshamrell-staging.pem

verifier:
  name: terraform
  format: doc
  groups:
  - name: chef_server
    tests:
      - oc_id_auth
    hostnames: chef_server_hostname
    username: ubuntu
  - name: supermarket_server
    tests:
      - config
    hostnames: supermarket_server_hostname
    username: ubuntu

suites:
  - name: chef_server
    run_list:
    attributes:
  - name: supermarket_server
    run_list:
    attributes:
