variable "access_key" {}
variable "secret_key" {}
variable "key_name" {}
variable "private_ssh_key_path" {}
variable "region" {}
variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "vpc_security_group_ids" {}
